### ISSUE TITLE
Broken Microsoft Icon with Working Link on '12-generative-ai.md' webpage

### ISSUE THREAD

**Issue by souvikrajsingh** [MicrosoftLearning/mslearn-ai-fundamentals#1]
# Module: Instructions
### **Description of issue**

The  Microsoft icon isn't visible on the top left which is supposed to redirect the use to the link - https://learn.microsoft.com/en-us/training/   , as shown in the snapshot below.

the link is working but the icon is broken

<img width="953" alt="issue-12-generative-ai md" src="https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/assets/81793119/2f4f329c-27bf-4980-af10-5bae3515ff4b">

its a simple fix

Repro steps:

1. Access the webpage "12-generative-ai.md" where the Microsoft icon is expected to be visible at the top left.
2. Observe that the Microsoft icon is not visible.
3. Attempt to click on the area where the Microsoft icon should be to confirm that it does not redirect the user to "https://learn.microsoft.com/en-us/training/" as intended.

**Comment by sherzyang** [comment]
Thanks @souvikrajsingh for pointing this out - I'm not able to replicate your issue but I'll keep it in mind for the future.

**Comment by souvikrajsingh** [comment]
> Thanks @souvikrajsingh for pointing this out - I'm not able to replicate your issue but I'll keep it in mind for the future.

thanks for looking into it , i have attached the link below for your reference, you can visit the site once!

[Visit Site ](https://microsoftlearning.github.io/mslearn-ai-fundamentals/Instructions/Labs/12-generative-ai.html#sign-into-bing
)
