### ISSUE TITLE
Lab 12b - Different options in the Copilot pane (Microsoft Edge)

### ISSUE THREAD

**Issue by afelix-95** [MicrosoftLearning/mslearn-ai-fundamentals#11]
# Module:
#### Step: 07

Description of issue

In the copilot pane, for "regular" accounts we only have the Creative/Balanced/Precise options for conversation style, without the GPT-4/GPT-4 Turbo options.

Repro steps:

![Screenshot 2024-04-29 182403](https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/assets/148110824/821f1b39-2c5a-47a3-98c6-c313fb10e5e7)

**Comment by dahans-msft2** [comment]
Replaced the images and rewrote step 7 for "regular" Copilot experience, not the Copilot Pro experience.
