### ISSUE TITLE
Unable to access Content Safety Studio

### ISSUE THREAD

**Issue by JacksonLiew101** [MicrosoftLearning/mslearn-ai-fundamentals#13]
# Module: Content Safety Studio
#### Step: Navigate the Content Safety Studio

Description of issue:
The Content Safety Studio is not accessible via the following links:
1. https://contentsafety.cognitive.azure.com/?azure-portal=true
2. https://contentsafety.cognitive.azure.com/

Repro steps:
1. Create a Content Safety resource in the Azure portal, based on 'Australia East' with free pricing tier using 'Azure for Students'.
2. Attempt to access the Content Safety Studio via the provided links.

**Comment by GoldenretriverYT** [comment]
This is not completed. It shows a blank page.

**Comment by ramakantsdebata** [comment]
> This is not completed. It shows a blank page.

+1
Shows up blank.

**Comment by Tomasz-Zdeb** [comment]
Hi,
As of December 31, 2024, I am still experiencing similar symptoms.

The links seem to be correct, they are in accordance with the official documentation: [Studio Quickstart](https://learn.microsoft.com/en-us/azure/ai-services/content-safety/studio-quickstart).

Obvious "fixes", like clearing cache/cookies and accessing the page from a different browser (I've tested Microsoft Edge, Mozilla Firefox and Google Chrome), do not resolve the issue.

---

I did not find any official information stating that the Content Safety Studio is down. It appears that it is not listed on the [Azure Status](https://azure.status.microsoft/en-us/status) page, so I am wondering what the correct way to monitor its status is. Submitting an Azure support ticket is not an option for me, as it requires a paid support plan. @sherzyang, do you know if there is any other way to inform Azure's team that the service may not be working correctly?

**Comment by EranTimothy-dev** [comment]
I have the same issue, but for some reason, I can access it through my mobile device and not my laptop. Deleting cookies and cache is a good idea as well though.
