### ISSUE TITLE
 knowledge-store container missing in my container

### ISSUE THREAD

**Issue by KristinBethea** [MicrosoftLearning/mslearn-ai-fundamentals#16]
# Module: Fundamentals of Knowledge Mining and Azure AI Search 
#### Step: 02
![AISearchTrainingKnowledge-Store-ContainerMissing](https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/assets/112720229/f01ec6be-5837-4339-aff5-29c64b0cb826)

Description of issue
coffee-reviews and coffee-skillset-image-projection are in my container, but  knowledge-store container is not.

Repro steps:
Follow the steps on Explore an Azure AI Search index (UI)
1.
1.
1.

**Comment by sherzyang** [comment]
Hi @KristinBethea, thanks for sharing. Unfortunately, I wasn't able to reproduce your issue. One thing you may want to try is go back to this section https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/blob/main/Instructions/Labs/11-ai-search.md#index-the-documents and go to steps 6 and 7. These steps instruct you to create a knowledge-store folder. I'm going to change the formatting of the steps to make the steps clearer. 
![image](https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/assets/19577448/116985f8-effc-4ecb-9a94-0bfe275990cb)

At step 7, double check what you selected in the Import Data wizard, You will need to select both **Documents** under "Azure table projections" and **Document** under "Azure blob projections". 
![image](https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/assets/19577448/4e67f701-e069-410d-86f6-e243037268d4)
 
 If you try again and still do not see the knowledge-store, please submit another bug. Thanks!
