### ISSUE TITLE
update the page with necessary changes

### ISSUE THREAD

**Issue by Shazad2023** [MicrosoftLearning/mslearn-ai-fundamentals#2]
Hello,

The Azure Machine Learning tutorial had a mistake in its typing, as shown in the picture. The threshold for the metric score has been set at two different values. It seems that only one of the threshold values of 0.85 or 0.085 is the correct value. Otherwise, it must be explained what the difference is between two kinds of threshold.

![Shot 0008](https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/assets/150153078/9490ba4f-b287-4387-ad21-081138ae0b9d)
# Module: 00
## Lab/Demo: 
00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by sherzyang** [comment]
Thanks @Shazad2023 for pointing that out. The correct configuration is **metric score threshold: 0.085**. I fixed it in the instructions.

**Comment by Shazad2023** [comment]
> Thanks @Shazad2023 for pointing that out. The correct configuration is **metric score threshold: 0.085**. I fixed it in the instructions.

To verify it, I must register again to have access via the Student Benefits option, which is taking up a lot of my time. BTW, I appreciate your correction.

**Comment by Shazad2023** [comment]
> Thanks @Shazad2023 for pointing that out. The correct configuration is **metric score threshold: 0.085**. I fixed it in the instructions.

I checked it. The correction has been made. Thank you very much.
