### ISSUE TITLE
Cannot test model in lab - Explore Automated Machine Learning in Azure Machine Learning

### ISSUE THREAD

**Issue by scottrhay** [MicrosoftLearning/mslearn-ai-fundamentals#21]
# Module: 01
#### Step: 2

Description of issue

Cannot test the model, Azure returns an error message that the model uses an outdated API. 

Repro steps:

Follow the lab, when following the Test the deployed service section, I get the following error message when opening the Test tab in Azure: 
  V1 deployment testing not supported
  This deployment is based on v1 API and doesn't support testing on the Studio. To get the key/token and invoke, please use 
  CLI/SDK/REST v1 API. Consider migrating to v2 managed online endpoint.

**Comment by jackmmcgarry** [comment]
I have the same issue. Have you figured out any resolution?

**Comment by sherzyang** [comment]
@scottrhay, @jackmmcgarry, let me work on this and find a solution, thanks for sharing.

**Comment by aparnakhadatkar** [comment]
Hi @sherzyang, I have the same issue. Have you found a solution?

**Comment by sherzyang** [comment]
Hi @scottrhay, @jackmmcgarry, @aparnakhadatkar, we have a solution. I will be updating the lab instructions later today. Here's a summary of the solution: 

At the end we see that we're using v1 which is not compatable with testing. To "use" v2 we need to change the type of input dataset. A tabular dataset is a v1 type of dataset. We need a MLTable dataset to "force" the UI to use the v2 SDK in the backend.

**Comment by sherzyang** [comment]
Hi @scottrhay, @jackmmcgarry, @aparnakhadatkar, unfortunately, the Studio does not support creating the MLTable dataset at this time. I am going to close this bug and put a note in the lab for now. Long-term, I will find an alternate solution.

**Comment by jannatfatima294** [comment]
im facing the same issue what should i do then?

**Comment by scottrhay** [comment]
Okay, it sounds like we just need to skip the testing part of the lab. 

Can you clarify what exactly v1 and v2 are referred to by this error message?

**Comment by jannatfatima294** [comment]
so should i just delete the workspace

**Comment by armaf002** [comment]
Same issues I've been having here as well
