### ISSUE TITLE
Cannot test model in lab - Explore Automated Machine Learning in Azure Machine Learning

### ISSUE THREAD

**Issue by aparnakhadatkar** [MicrosoftLearning/mslearn-ai-fundamentals#23]
# Module: 01
#### Step: 2

Description of issue

Cannot test the model, Azure returns an error message that the model uses an outdated API.

Repro steps:

Follow the lab, when following the Test the deployed service section, I get the following error message when opening the Test tab in Azure:
V1 deployment testing is not supported
This deployment is based on v1 API and doesn't support testing on the Studio. To get the key/token and invoke it, please use
CLI/SDK/REST v1 API. Consider migrating to a v2-managed online endpoint.

Please let me know if you have any updates on this as there is an update in the repo so we can tested the model again but  I am facing the same issue again.

And again **https://aka.ms/bike-rentals** This link is not working we are not able to download 2  files as mentioned in lab 1.

**Comment by loglux** [comment]
You can find bike-rentals files (MLTable and daily-bike-share.csv) here:
https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/tree/main/data/ml/bike-data

**Comment by sherzyang** [comment]
@aparnakhadatkar, the instructions have been updated to address the issue you are referring to. Please use the current instructions https://microsoftlearning.github.io/mslearn-ai-fundamentals/Instructions/Labs/01-machine-learning.html and start from the beginning. The issue is in the file type for the data file, so you need to re-create that using the current instructions. Please log another bug if you are still experiencing issues. Thanks!

**Comment by loglux** [comment]
what about his JSON code, which didn't work?

 {
   "Inputs": { 
     "data": [
       {
         "day": 1,
         "mnth": 1,   
         "year": 2022,
         "season": 2,
         "holiday": 0,
         "weekday": 1,
         "workingday": 1,
         "weathersit": 2, 
         "temp": 0.3, 
         "atemp": 0.3,
         "hum": 0.3,
         "windspeed": 0.3 
       }
     ]    
   },   
   "GlobalParameters": 1.0
 }

**Comment by loglux** [comment]
and the link https://aka.ms/bike-rentals still leads to 404 error
