### ISSUE TITLE
Cannot Test Model in Lab - Explore Automated Machine Learning in Azure Machine Learning (Reopened)

### ISSUE THREAD

**Issue by loglux** [MicrosoftLearning/mslearn-ai-fundamentals#25]
https://microsoftlearning.github.io/mslearn-ai-fundamentals/Instructions/Labs/01-machine-learning.html

**Cannot test the model:** Azure returns an error message. When testing the model, the following error message appears: "Failed to test model: A value is not provided for the 'input_data' parameter."

**Broken link:** The link to download the bike rental files (https://aka.ms/bike-rentals) results in a 404 error, preventing the download of the necessary files.

Despite following the updated instructions provided in the previous issue, the problem persists.
The broken link issue remains unresolved, and it prevents the completion of the lab.

**Comment by sherzyang** [comment]
Thanks @loglux, I will take a look at that.

**Comment by sherzyang** [comment]
@loglux , the link to the data now works again. Let me work on the other issues.

**Comment by loglux** [comment]
Attempting to download the bike rental files from https://aka.ms/bike-rentals now works, but it only downloads daily-bike-share.csv and does not include the MLTable file, which is required to complete the lab

**Comment by sherzyang** [comment]
@loglux, you are right, I fixed the issue and now https://aka.ms/bike-rentals downloads the folder with the two files.

**Comment by sherzyang** [comment]
Confirming that the endpoint can be created, but the test runs into an unexpected error in the scoring script, so we are still blocked.

**Comment by sherzyang** [comment]
@loglux, confirming this is fixed. Learners can test with the provided instructions and JSON now.
