### ISSUE TITLE
Error when testing deployed AutoML model for bike rentals

### ISSUE THREAD

**Issue by paulahollander** [MicrosoftLearning/mslearn-ai-fundamentals#26]
# Module: 01
#### Step: 4

Description of issue

After replacing the template JSON with the input data given and then clicking the Test button, the following error message shows:

"Failed to test model: An unexpected error occurred in scoring script. Check the logs for more info."

Repro steps:

1. Created Automated ML job as per exercise guide then submitted training job
1. Best model algorithm name was VotingEnsemble, deployed it to new endpoint - note that my Azure quota only allowed 2 instances of Standard_DS3_v2 
1. Attempted to test with the supplied JSON

**Comment by sherzyang** [comment]
@paulahollander , I just pushed a fix to this issue. You should be able to test with the provided JSON now.

**Comment by paulahollander** [comment]
Hi Sherry,

Thanks. I just redid the exercise and everything worked.

Kind regards,

Paula
________________________________
