### ISSUE TITLE
Graphing not working in ML exercises

### ISSUE THREAD

**Issue by mpopejoy-dxc** [MicrosoftLearning/mslearn-ai-fundamentals#27]
# Module: Create and understand classification models in machine learning
#### Step: 2

Graphing isn't working in several excercises. First encountered as listed above and in Repro steps. So far, the other exercises in the ML fundamental tracks that use graphing have the same issue. 

Repro steps:

1. https://learn.microsoft.com/en-us/training/modules/understand-classification-machine-learning/3-exercise-build-regression-model
2. run first cell (import pandas, etc.)
3. run 2nd cell (import graphing). There's the following error on graphing: 'Import "graphing" could not be resolvedPylance(reportMissingImports)'
4. Results in following;
TypeError: MathJax.Hub is undefined
TypeError: this.Plotly.newPlot is not a function
TypeError: this.Plotly.newPlot is not a function
TypeError: this.Plotly.newPlot is not a function

**Comment by sherzyang** [comment]
@mpopejoy-dxc, the issue you are facing is for a lab that is not part of this repo. Unfortunately, I won't be able to address it on my end. For issues related to the module on Learn, please submit your issue at [Ask a question](https://learn.microsoft.com/en-us/answers/questions/ask/?id=aHR0cHM6Ly9taWNyb3NvZnQtZGV2cmVsLnBvb2xwYXJ0eS5iaXovRGV2UmVsTWFjaGluZUdlbmVyYXRlZENvbXBvdW5kVGF4b25vbXkvODQ0YWI2NTEtNzBmMi00YjUzLTkxZWYtZTkzMjZhZWZjMDZl&styleGuideLabel=Azure%20Training) on Microsoft Q&A.
