### ISSUE TITLE
Some of the images had broken links on Explore Azure OpenAI Service

### ISSUE THREAD

**Issue by akiko-pusu** [MicrosoftLearning/mslearn-ai-fundamentals#29]
I referred to this page for learning. 

https://microsoftlearning.github.io/mslearn-ai-fundamentals/Instructions/Labs/13-azure-openai.html

Then I noticed that some of the images had broken links.
It appeared that the target images were removed from the repository in this commit: commit 8de58ea
Is this intended for future replacement or something else?

Screenshot:
-------
![image](https://github.com/user-attachments/assets/6d3552fa-2c5d-4410-8326-f9eac11c403c)
-------

Thank you for providing great content.
I hope this would be some of help.

-------

# Module: 00
#### Step: 00

Description of issue

Repro steps:

**Comment by sherzyang** [comment]
@akiko-pusu thanks for sharing, I am actually going to retire this lab. Microsoft has merged the features of Azure OpenAI Studio into Azure AI Studio. You will find a similar exercise to this one using Azure AI Studio attached to the learning material: 

Learn module: https://learn.microsoft.com/en-us/training/modules/introduction-to-azure-ai-studio/

Lab: https://microsoftlearning.github.io/mslearn-ai-studio/Instructions/01-Explore-ai-studio.html

I'll add some information at the beginning of this lab to help redirect users. 

Thanks, 
Sherry
