### ISSUE TITLE
Content Safety Studio page constantly refreshing

### ISSUE THREAD

**Issue by IriW** [MicrosoftLearning/mslearn-ai-fundamentals#33]
# Module: Fundamentals of Azure AI services
#### Step: 1

Description of issue
Can't try out test run. When I'm not signed in, the Content Safety Studio page looks good but "try out" is not active (and it's ok), but when I sign in, then I can't click anything, because the page is constantly refreshing. I tried to clear the entire cache, history and restart laptop - nothing helps.
Browser: Mozilla Firefox, system: linux mint

Repro steps:

1. Go to lab page [https://contentsafety.cognitive.azure.com/](url)
2. Sign in

**Comment by GraemeMalcolm** [comment]
Non-repro for me I'm afraid.
