### ISSUE TITLE
Fundamentals of Knowledge Mining and Azure AI Search -Exercise - Explore an Azure AI Search index (UI)

### ISSUE THREAD

**Issue by OscarValerock** [MicrosoftLearning/mslearn-ai-fundamentals#4]
# Module: 00
### Task: Learn more
https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/blob/main/Instructions/Labs/11-ai-search.md

Description of issue
Invalid link - 404

Repro steps:
The  link "Azure AI Search service page" is invalid. 
[Azure AI Search service page](https://microsoftlearning.github.io/azure/search/search-what-is-azure-search).

**Comment by sherzyang** [comment]
Thanks @OscarValerock! I have pushed a fix.
