### ISSUE TITLE
`search=*&$count=true` in the *Explore an Azure AI Search index (UI)* is not working as expected

### ISSUE THREAD

**Issue by joseville1001** [MicrosoftLearning/mslearn-ai-fundamentals#5]
# Module: 11
## Lab/Demo: 11

The [**Explore an Azure AI Search index (UI)**](https://microsoftlearning.github.io/mslearn-ai-fundamentals/Instructions/Labs/11-ai-search.html) lab has some issues.

Description of issue
In step 2 of the **Query the index** section of the lab, we are told to input the search query `search=*&$count=true` and that it should return *"all the documents in the search index, including a count of all the documents in the @odata.count field."*. But this is not happening. Instead the returned result is

```
{
  "@odata.context": "https://<ai search resrc name>.search.windows.net/indexes('coffee-index')/$metadata#docs(*)",
  "value": []
}
```

A similar issue was raised for Lab 22 of AI-102 [here](https://github.com/MicrosoftLearning/AI-102-AIEngineer/issues/247), which mentions a fix: select "JSON view" from View and input the following into the JSON query editor:

```
}
  "search": "*",
  "count": true
}
```

However, when I tried

```
{
  "search": "*",
  "count": true,
  "locations": "Chicago"
}
```

the results returned all 9 reviews (`@odata.count": 9`), including those that don't mention Chicago.

Repro steps:

1. Follow the [**Explore an Azure AI Search index (UI)**](https://microsoftlearning.github.io/mslearn-ai-fundamentals/Instructions/Labs/11-ai-search.html) lab until and including step 2 of the **Query the index** section.

**Comment by sherzyang** [comment]
Thanks so much @joseville1001! I tested out the lab and will update the search queries. 

Thanks for finding the AI-102 fix, that first one is spot on. 

Based on that one, the other two are: 

`{
  "search": "location:'Chicago'",
  "count": "true"
}`
`{
  "search": "sentiment:'negative'",
  "count": "true"
}`
